# Numpy
> - stands for numerical python
> - provides array

## Array
> - collection of homogenous elements
> - faster than __list__
> - Numpy allows **Broadcasting**,i.e, each elemnet can be multiplied by a contsant without using for loop
> - less space compared to list


In [5]:
import numpy as np

lst = [10,9,11,13,45,23]
arr = np.array(lst)
print(arr,"\n",type(arr))

[10  9 11 13 45 23] 
 <class 'numpy.ndarray'>


In [6]:
import time
st = time.time()
lst = [i for i in range(1000000)]
for i in range(len(lst)):
    lst[i]*=6
tt = time.time() - st
print(tt)

0.3419468402862549


In [15]:
import time
import numpy as np
st = time.time()
arr = np.arange(1,1000000)
arr*6
tt = time.time() - st
print(tt)

0.007944822311401367


### Array Operations

In [14]:
arr = np.arange(1,1000000)
print(arr.size)    # gives size of the array
print(len(arr))
print(arr.shape)   # dimesnsion of the array
print(arr.dtype)   # returns type of elements

999999
999999
(999999,)
int32


In [28]:
ar = np.array(6)     # single value
print(ar.ndim)
ar = np.array([6])   # passing a itterable (list)
print(ar.ndim)
ar1 = np.array([[6,3,4,5,6,7],[1,2,3,4,6,5],[9,8,87,2,65,5]])   # passing a itterable (list) which is 2 dimensional 
print(ar1.ndim)

0
1
2


### Array Upcasting
> int --> float --> complex --> string

In [25]:
import numpy as np

In [27]:
ar = np.array([1,2,3,4,5,3.4])
print(ar.dtype)

float64


In [29]:
ar = np.array([1,2+7j,3,4,5,3.4])
print(ar.dtype)

complex128


In [32]:
ar = np.array([1,2,"String",4,5,3.4])
print(ar.dtype)                #U32 means unicode with 32 as size

<U32


### Reshape Function
> change the dimension of an array

In [33]:
import numpy as np

In [34]:
ar = np.array([1,2,3,4,5,6,7,8,9])
print(ar)
ar = ar.reshape(3,3)
print(ar)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Arange Function
> same as range(start,stop,stepsize) but here it will return a array as output

In [40]:
import numpy as np

In [18]:
lst = list(range(1,50,6))
print(lst)
ar = np.arange(1,50,6)
print(ar)

[1, 7, 13, 19, 25, 31, 37, 43, 49]
[ 1  7 13 19 25 31 37 43 49]


### Linspace Function
> create in a range equally spaced value array

In [47]:
import numpy as np
np.linspace(1,10,20)  # it will take 10 also not like a range

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

### Zeros Function
> generating array of zeros in given shape

In [51]:
z = np.zeros((3,4))     # it will give float as default
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [50]:
z = np.zeros((3,4),dtype=int)
print(z)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### Ones Function

In [52]:
z = np.ones((3,4),dtype=int)
print(z)    

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


### Eye Function
> create a identity metrix - diagonals are all 1 and rest 0

In [57]:
z = np.eye(3,3,dtype=int)  # note: syntax is different from all the above
print(z)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


## Array of Random Numbers

### Random.random function
> create a 1-D array with values between 0 and 1

In [63]:
z = np.random.random(10)
print(z)
print()
z = np.random.random(9).reshape(3,3)   # use reshape to change dimesnsion
print(z)

[0.01110297 0.25407325 0.74158005 0.3363592  0.63717021 0.52585901
 0.78560477 0.88931409 0.18242553 0.35821512]

[[0.70605462 0.41507117 0.8953012 ]
 [0.98159416 0.4172217  0.21061375]
 [0.72657026 0.18572686 0.88942793]]


### Random.rand Function
> - create a random array with given shape
> - __random.rand(block(dimesnion) , rows , columns)__

In [71]:
z = np.random.rand(2,3,10)
print(z)

[[[0.78330621 0.54758975 0.61149529 0.70846099 0.5252535  0.26980448
   0.95744019 0.53994448 0.2173599  0.10087171]
  [0.43737894 0.67468246 0.15326197 0.37555194 0.77068322 0.81196528
   0.4209989  0.42058357 0.2370632  0.93159237]
  [0.79391071 0.8068927  0.49673795 0.59573323 0.73750777 0.23701231
   0.57945851 0.11164759 0.0807775  0.36291006]]

 [[0.96872642 0.47585861 0.63363367 0.53235528 0.00207209 0.16065109
   0.70198128 0.13629833 0.77611326 0.41897026]
  [0.75223072 0.93940425 0.2733287  0.24325736 0.24558334 0.22383311
   0.61827742 0.26734499 0.42576375 0.78325731]
  [0.0048064  0.89244769 0.06802999 0.87440497 0.94156424 0.6118637
   0.33687642 0.42671002 0.99823533 0.93884224]]]


In [73]:
z = np.random.rand(2,10)
print(z)

[[0.26896303 0.46486399 0.03179718 0.39990629 0.1316488  0.13088358
  0.86427065 0.55543689 0.16387151 0.37208312]
 [0.93397054 0.45230793 0.89035329 0.6978723  0.46732143 0.52966865
  0.60319082 0.95807868 0.27543279 0.94034566]]


### Random.randint function
> - returns an array of value lies in a range
> - __random.randint(start_num , end_num , num_values_between_start&end)__

In [74]:
z = np.random.randint(1,11,15)
print(z)
z = np.random.randint(1,11,15).reshape(3,5)
print(z)

[ 6  1  5 10 10  3  2  4  1  2  9  9  1  5  5]
[[8 9 1 9 6]
 [2 5 2 5 6]
 [2 7 2 3 5]]


### Random.seed function
> - fix the random seed state
> - once random state seed is set we get same random value every time
> - fixes the random state only for the next execution

In [97]:
np.random.seed(270)
np.random.randint(10,100,10)

array([42, 82, 33, 57, 16, 85, 37, 63, 30, 56])

In [82]:
np.random.seed(270)   # if in 2 cell it will only work for one next execution, second time running below line wont work

In [91]:
np.random.randint(10,100,10)

array([51, 94, 21, 92, 79, 91, 11, 61, 30, 69])

In [96]:
np.random.seed(2**32-1)  # last random state
np.random.randint(10,100,10)

array([45, 44, 22, 81, 62, 74, 96, 99, 42, 21])

## 2D Array

In [13]:
import numpy as np
lst = [[1,2,3],[4,5,6],[7,8,9]]
ar = np.array(lst)
print(ar)
print(ar.ndim)
print(ar.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [51]:
x = np.random.randint(1,100,20).reshape(4,5)
x = np.array(x)
print(x)
print(x.shape)
print(x[0])
print(x[0,2])
print(x[0:2])

[[94 50 90 92 32]
 [15 96 46  1 59]
 [46 72 13 26 81]
 [10 86 41 48 12]]
(4, 5)
[94 50 90 92 32]
90
[[94 50 90 92 32]
 [15 96 46  1 59]]


## 3D Array

In [10]:
import numpy as np
lst = [[[1,2,3],[4,5,6],[7,8,9]]]
ar = np.array(lst)
print(ar)
print(ar.shape) # (dimension,rows,colums)
print(ar.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
(1, 3, 3)
3


In [12]:
lst = [[[1,2],[4,5],[7,8]],[[9,8],[6,5],[3,2]]]
ar = np.array(lst)
print(ar)
print(ar.shape) 
print(ar.ndim)

[[[1 2]
  [4 5]
  [7 8]]

 [[9 8]
  [6 5]
  [3 2]]]
(2, 3, 2)
3


In [72]:
ar = np.random.randint(10,100,3*3*4).reshape(3,3,4)   #reshape(block,rows,colums)
print(ar)
print("\n First element:",ar[0][0][0])
print("\n First element:",ar[0,0,0])
print("\n Second element:",ar[-1][-1][-1])
print("\n Element at location -2,-2,-3:",ar[-2][-2][-3])
print("\nar[0::2 , 0:2 , 0:3]:\n",ar[0::2 , 0:2 , 0:3])
print("\nar[1]:",ar[1])
print("\nFirst 2 rows:\n",ar[:,0:2,:])
print("\nLast 2 rows:\n",ar[:,1:3,:])
print("\nar[1:2,1,2:4]:",ar[1:2,1,2:4])

[[[18 36 20 79]
  [29 71 47 30]
  [65 22 82 30]]

 [[17 46 27 49]
  [10 92 93 47]
  [46 85 96 83]]

 [[22 33 64 66]
  [81 96 75 46]
  [22 10 40 84]]]

 First element: 18

 First element: 18

 Second element: 84

 Element at location -2,-2,-3: 92

ar[0::2 , 0:2 , 0:3]:
 [[[18 36 20]
  [29 71 47]]

 [[22 33 64]
  [81 96 75]]]

ar[1]: [[17 46 27 49]
 [10 92 93 47]
 [46 85 96 83]]

First 2 rows:
 [[[18 36 20 79]
  [29 71 47 30]]

 [[17 46 27 49]
  [10 92 93 47]]

 [[22 33 64 66]
  [81 96 75 46]]]

Last 2 rows:
 [[[29 71 47 30]
  [65 22 82 30]]

 [[10 92 93 47]
  [46 85 96 83]]

 [[81 96 75 46]
  [22 10 40 84]]]

ar[1:2,1,2:4]: [[93 47]]


## Functions for Array

In [83]:
np.random.seed(2*34-1)
x = np.random.randint(10,100,3*4*3).reshape(3,4,3)
print(x)
print("Sum:",np.sum(x))
print("Max:",np.max(x))
print("Min:",np.min(x))
print("Mean:",np.mean(x))
print("Mean:",np.sum(x)/x.size)
print("Median:",np.median(x))  # middle value

[[[77 63 84]
  [79 17 99]
  [19 45 32]
  [99 55 45]]

 [[33 63 45]
  [64 41 65]
  [55 43 52]
  [68 36 29]]

 [[65 66 49]
  [44 63 32]
  [38 56 51]
  [32 46 66]]]
Sum: 1916
Max: 99
Min: 17
Mean: 53.22222222222222
Mean: 53.22222222222222
Median: 51.5
